//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenVerInfo {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GenVerInfo.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;RSAKeyValue&gt;
        ///	&lt;Modulus&gt;qgygjOOrPVoXdytZARmu2f8vV0omYqeclHBSIpeon7xIsYx8TiCOiecUD3NfnANdaneFOZZ1Att4rOLrDewhJnT6MOI4WBdXzpF36PMtL4ndIIGEYu0zOGO+Qi1sXPZWshrueO2IYIt9NK5RBI8YeejYJDU2BaqBE5ZsXFiDQ6o5fZftC57j1vD88Gg/V50klq00Q0q4vm0939B/HYz45ZzXZvn26pbUDyLH7ZqxacSTfdGlDN7pQ+Q7vaYOqnCtbGD8vfujV/X2LlqCpKc5iPD6Dx3iINOhByfyZ5udDtYaxbZKSumfI2OHBQT+L6Jw2RuMcH40n1aXdJaJ1KLCQMqbmOOEwM1ejbXgWtPBvo5oYjKgUUtKnBOHjZL2d3jKIWy7SSAIWmd0wDpIuA1KSORjNslgEzMRCkz5TAg9makAQ3e764FBJsy9anR2Yw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
    }
}
